<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>html</string>
	</array>
	<key>injections</key>
	<dict>
		<key>text.html.volt - (meta.embedded.block.volt | meta.embedded.line.volt | comment)</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(^\s*)(?=&lt;%+#(?![^%]*%&gt;))</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.whitespace.comment.leading.volt</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?!\G)(\s*$\n)?</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.whitespace.comment.trailing.volt</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(^\s*)(?=&lt;%(?![^%]*%&gt;))</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.whitespace.embedded.leading.volt</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?!\G)(\s*$\n)?</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.whitespace.embedded.trailing.volt</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tags</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tags</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>name</key>
	<string>HTML (Volt)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>&lt;%+#</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.begin.volt</string>
						</dict>
					</dict>
					<key>end</key>
					<string>%&gt;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.end.volt</string>
						</dict>
					</dict>
					<key>name</key>
					<string>comment.block.volt</string>
				</dict>
			</array>
		</dict>
		<key>tags</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\{\{)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.begin.volt</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>source.ruby.volt</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>source.ruby.volt</string>
					<key>end</key>
					<string>(\}\})</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.end.volt</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>source.ruby.volt</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.embedded.block.volt</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.volt</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(#).*?(?=-?%&gt;)</string>
							<key>name</key>
							<string>comment.line.number-sign.volt</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.ruby.volt</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\{\{)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.begin.volt</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>source.ruby.volt</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>source.ruby.volt</string>
					<key>end</key>
					<string>(\}\})</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.end.volt</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>source.ruby.volt</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.embedded.line.volt</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.volt</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(#).*?(?=-?%&gt;)</string>
							<key>name</key>
							<string>comment.line.number-sign.volt</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.ruby.volt</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.volt</string>
	<key>uuid</key>
	<string>9BE40B82-11BC-4D89-9B88-49EBEE3B1CAC</string>
</dict>
</plist>
